spring:
  application:
    name: reactive-api
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      sslMode: ${DB_SSL_MODE}
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
